module.exports = {
  lorem: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  candidates:[
      {
        account:"a0qu14zoh9nn",
        votes:9,
        rep:45,
        vote:false,
        profile:{"name":"Zaraza","surname":"Olariu","gender":"female","region":"Romania"},
        skills:[7,4,2,7,1,9],
        contact:{
          email:"",
          telegram:"",
          discord:"",
          weChat:""
        }
      },
      {
        account:"o2wga55w11nb",
        votes:9,
        rep:45,
        vote:false,
        profile:{"name":"Baranyi","surname":"Helga","gender":"female","region":"Hungary"},
        skills:[2,3,3,4,6,7],
        contact:{
          email:"",
          telegram:"",
          discord:"",
          weChat:""
        }
      },
      {
        account:"md5f53jboj22",
        votes:9,
        rep:45,
        vote:false,
        profile:{"name":"Zaraza","surname":"Olariu","gender":"female","region":"Romania"},
        skills:[2,5,3,2,9,7],
        contact:{
          email:"",
          telegram:"",
          discord:"",
          weChat:""
        }
      },
      {
        account:"yfc36fpwnacg",
        votes:9,
        rep:45,
        vote:false,
        profile:{"name":"Laurențiu","surname":"Cernea","gender":"male","region":"Romania"},
        skills:[2,5,3,6,8,7],
        contact:{
          email:"",
          telegram:"",
          discord:"",
          weChat:""
        }
      },
      {
        account:"10zo5e1fr0p6",
        votes:9,
        rep:45,
        vote:false,
        profile:{"name":"Vəfa","surname":"Yusifzadə","gender":"female","region":"Azerbaijan"},
        skills:[9,4,6,2,6,7],
        contact:{
          email:"",
          telegram:"",
          discord:"",
          weChat:""
        }
      },
      {
        account:"7hd4827tkyid",
        votes:9,
        rep:45,
        vote:false,
        profile:{"name":"Lennard","surname":"Walter","gender":"male","region":"Germany"},
        skills:[2,5,4,1,7,7],
        contact:{
          email:"",
          telegram:"",
          discord:"",
          weChat:""
        }
      },
      {
        account:"qk9eqqvk8rmp",
        votes:9,
        rep:45,
        vote:false,
        profile:{"name":"Rafael","surname":"Fuentes","gender":"male","region":"Spain"},
        skills:[2,5,1,6,4,3],
        contact:{
          email:"",
          telegram:"",
          discord:"",
          weChat:""
        }
      },
      {
        account:"kq93pcsnonor",
        votes:9,
        rep:45,
        vote:false,
        profile:{"name":"Adonis","surname":"Greceanu","gender":"male","region":"Romania"},
        skills:[2,5,3,2,9,7],
        contact:{
          email:"",
          telegram:"",
          discord:"",
          weChat:""
        }
      },
      {
        account:"xxsssnv1vfw1",
        votes:9,
        rep:45,
        vote:false,
        profile:{"name":"Λουΐζα","surname":"Αλαφούζος","gender":"female","region":"Greece"},
        skills:[6,5,2,1,3,5],
        contact:{
          email:"",
          telegram:"",
          discord:"",
          weChat:""
        }
      },
      {
        account:"y4rsdhts6hnj",
        votes:9,
        rep:45,
        vote:false,
        profile:{"name":"Lilou","surname":"Simon","gender":"female","region":"France"},
        skills:[2,4,2,3,2,4],
        contact:{
          email:"",
          telegram:"",
          discord:"",
          weChat:""
        }
      },
  ]
}